import type { NewsItem } from '@/types'

const MOCK_DATA: Record<string, string[]> = {
  weibo: [
    '国务院召开全体会议部署重点工作',
    '神舟飞船成功对接天宫空间站',
    '今年春节档票房创历史新高',
    '多地出台住房补贴新政策',
    '知名演员参演新剧引发热议',
    '全国高考报名人数再创新高',
    '某城市地铁新线路正式开通',
    '网红餐厅因食品安全问题被查',
    '国内新能源汽车销量突破百万',
    '大学生创业项目获千万融资',
  ],
  zhihu: [
    '为什么说 DeepSeek 是中国 AI 的突破？',
    '普通人如何在 10 年内实现财务自由？',
    '人类究竟需要睡多少小时才算够？',
    '中国的房价还会继续涨吗？',
    '学编程对普通人的职业有多大帮助？',
    '为什么越来越多年轻人选择不婚不育？',
    '如何看待当前的就业形势？',
    '量子计算机会在 10 年内取代传统计算机吗？',
    '中医和西医应该如何取长补短？',
    '哪些职业在 AI 时代最不容易被替代？',
  ],
  baidu: [
    '今日天气预报',
    '股票行情实时查询',
    '国内最新新闻头条',
    '热门电视剧在线观看',
    '高考志愿填报指南',
    '新冠疫情最新动态',
    '双十一购物节攻略',
    '北京上海最新限行政策',
    '人民币汇率今日走势',
    '社保医保查询办理',
  ],
  bilibili: [
    '【4K】中国最美的100个地方航拍合集',
    '我用一年时间学会了钢琴，来听听成果',
    '深度解析：为什么年轻人越来越难找工作',
    '【纪录片】改变世界的十项发明',
    '自制迷你水族箱，养了20种稀有鱼类',
    'AI 绘画已经超越人类画师了吗？',
    '一个人骑行318国道全程记录',
    '花 3 万块装修出了梦想中的书房',
    '零基础学 Python，30 天能到什么水平？',
    '世界上最难攀登的十座山峰',
  ],
  sspai: [
    '用 Obsidian 打造个人知识管理系统完全指南',
    '2024 年值得购买的 10 款效率工具',
    'iPhone 隐藏功能大全：你可能还不知道的技巧',
    '如何用 Notion 管理你的读书笔记',
    '从零开始搭建个人博客：域名、服务器、建站全流程',
    'Mac 必装软件推荐（2024 更新版）',
    '智能家居入门：如何选择适合自己的方案',
    'Cursor AI 编辑器使用技巧分享',
    '用 NAS 打造家庭影音中心完全教程',
    '年度总结：2024 年生产力工具变化',
  ],
  '36kr': [
    '红杉资本发布 2024 年 AI 创业报告',
    '字节跳动海外业务增速超预期',
    '造车新势力洗牌加速，谁能活到最后？',
    '万亿级赛道：AI 应用层的创业机会在哪里',
    '独家：某独角兽完成新一轮 5 亿美元融资',
    '大模型价格战白热化，行业毛利率腰斩',
    '消费降级还是理性消费？2024 年零售趋势解读',
    '出海东南亚的中国企业：机遇与挑战并存',
    '智能驾驶商业化提速，L3 落地还需几年？',
    '医疗 AI 迎来爆发期，哪些方向最值得关注',
  ],
  xueqiu: [
    'A股三大指数集体收涨，创业板涨超2%',
    '港股恒生指数强势反弹，科技股领涨',
    '美联储会议纪要释放信号，市场如何解读',
    '新能源板块回调，是买入时机吗？',
    '银行股估值见底了吗？机构这样看',
    '人民币兑美元汇率走势分析',
    '公募基金年度排名揭晓，这些基金经理值得关注',
    '房地产政策持续发力，相关股票怎么看',
    '北向资金连续净流入，外资在买什么',
    '个人投资者如何在震荡市中保全资产',
  ],
  github: [
    'deepseek-ai/DeepSeek-V3 · 开源大语言模型',
    'anthropics/claude-code · AI 编程助手',
    'microsoft/TypeScript · TypeScript 语言',
    'vuejs/vue · 渐进式 JavaScript 框架',
    'vitejs/vite · 下一代前端工具链',
    'tailwindlabs/tailwindcss · CSS 框架',
    'supabase/supabase · 开源 Firebase 替代品',
    'vercel/next.js · React 全栈框架',
    'pytorch/pytorch · 机器学习框架',
    'astral-sh/uv · 极速 Python 包管理器',
  ],
  v2ex: [
    '分享一个我用了三年的效率工作流',
    '请问大家怎么看现在的就业市场？',
    '独立开发两年，月收入终于过万了',
    '推荐几个国内可以稳定访问的 AI 工具',
    '35岁被裁，该怎么规划下一步？',
    '有没有人在用 AI 写代码？效率提升多少？',
    '求推荐一款好用的密码管理器',
    '今天面试了五家公司，聊聊我的感受',
    '关于远程工作的一些真实体验分享',
    '买了 MacBook Pro，值不值这个价',
  ],
  producthunt: [
    'Cursor AI - The AI-first Code Editor',
    'Perplexity Pro - AI Search Engine',
    'Notion AI - Write, plan, analyze',
    'Linear - Issue tracking for modern teams',
    'Raycast - Supercharged productivity',
    'Arc Browser - A better way to browse',
    'Clerk - Authentication for modern apps',
    'Resend - Email for developers',
    'Trigger.dev - Open-source background jobs',
    'Cal.com - Open Scheduling Infrastructure',
  ],
  reddit: [
    'TIL that octopuses have three hearts and blue blood',
    'What skill did you learn during COVID that you still use?',
    'The James Webb telescope just revealed something extraordinary',
    'Ask Reddit: What is something that used to be normal 20 years ago?',
    'Programmers of Reddit: What is your biggest pet peeve?',
    'This AI can now generate a full movie from text prompts',
    'What are some underrated countries to visit?',
    'My dog learned to open the fridge. Send help.',
    'Scientists discover new deep-sea creature never seen before',
    'What book genuinely changed how you think about life?',
  ],
  douyin: [
    '街头采访：你的月薪够花吗',
    '这道菜只需五分钟，好吃到停不下来',
    '农村小伙逆袭记，年收入百万的秘密',
    '当代年轻人的搞笑日常合集',
    '挑战一个月不点外卖，我省了多少钱',
    '深夜的城市真的很美，带你看不一样的北京',
    '这款国产手机真的吊打苹果吗？亲测告诉你',
    '宠物狗第一次看见大海的反应太可爱了',
    '手残党也能学会的三款超简单发型',
    '二手车市场乱象曝光，买车前必看',
  ],
  toutiao: [
    '重磅！国家出台新政策扶持中小企业',
    '独家：某知名企业家接受采访谈未来规划',
    '全球最大的AI芯片发布，性能碾压英伟达',
    '00后整顿职场：这些事我们真的不会忍',
    '城市内卷：北上广深的年轻人去哪了',
    '今年最火的旅游目的地排行榜出炉',
    '警惕！这种诈骗手法又在蔓延，已有多人上当',
    '医学突破：科学家找到了肥胖症的关键基因',
    '最新就业数据发布：这些行业依然在扩招',
    '网红经济降温，MCN机构大裁员',
  ],
  eastmoney: [
    '沪深两市今日成交额突破1.2万亿',
    '央行宣布降准0.5个百分点',
    '半导体板块集体拉升，多只个股涨停',
    '外资大幅增持A股，看好哪些方向',
    '2024年公募基金规模首破30万亿',
    '房地产龙头发布业绩预报，超市场预期',
    '锂电池概念股异动，产业链受益股梳理',
    '国内通胀数据出炉，市场影响几何',
    '券商板块爆发，背后逻辑是什么',
    '港股通净买入创新高，南向资金偏好曝光',
  ],
  cailian: [
    '【财联社】美联储官员暗示年内或有两次降息',
    '【电报】特斯拉在华销量环比下滑，竞争加剧',
    '【快讯】国内CPI数据出炉，同比上涨0.3%',
    '【独家】某头部券商完成新一轮增资扩股',
    '【电报】黄金突破3100美元/盎司，创历史新高',
    '【快讯】人民币兑美元中间价较上日调升108个基点',
    '【电报】A股三大指数午后拉升，沪指涨超1%',
    '【快讯】国家发改委：加快推进重大基础设施投资',
    '【电报】油价小幅回调，布伦特原油跌0.8%',
    '【快讯】银行间市场资金面整体宽松',
  ],
  wallstreet: [
    '美联储会议纪要：对通胀走势仍存分歧',
    '科技股领跌，纳斯达克指数单日下挫2.3%',
    '欧洲央行按兵不动，市场对降息预期降温',
    '日元汇率触及近期低点，日本央行口头干预',
    '全球供应链压力指数降至2021年以来最低',
    '巴菲特旗下伯克希尔一季度持仓大幅调整',
    '中东地缘政治升温，原油期货上涨逾3%',
    '苹果Vision Pro销量不及预期，分析师下调目标价',
    '美国就业数据超预期，降息时间表或推迟',
    '高盛：人工智能基础设施投资将达万亿美元级别',
  ],
  sina: [
    'A股早盘：沪指高开高走，科技板块领涨',
    '国内外汇储备规模创近两年新高',
    '多家银行下调存款利率，理财市场格局生变',
    '两会政府工作报告：今年GDP目标增长5%左右',
    '证监会出台新规，加强上市公司信息披露',
    '保险资金入市规模扩大，险资青睐哪些板块',
    '上交所：积极推动科创板高质量发展',
    '北向资金连续三日净流入，合计超200亿元',
    '地产板块异动拉升，政策预期持续升温',
    '人民币国际化提速，跨境结算规模大幅增长',
  ],}

export function getMockItems(sourceId: string): NewsItem[] {
  const titles = MOCK_DATA[sourceId] ?? MOCK_DATA.weibo
  return titles.map((title, i) => ({
    id: `${sourceId}-${i}`,
    title,
    url: '#',
    extra: { info: '演示数据' },
  }))
}
